### ISSUE TITLE
mat--switcher halts on *.scss files (Reference to angular/material2 #7520)

### ISSUE THREAD

**Issue by volei** [angular/material-update-tool#12]
[Ref. to angular/material2 #7520](https://github.com/angular/material2/issues/7520#issuecomment-334289900):
This would need to be changed here, I guess. See the link.

**Comment by DevVersion** [comment]
Thanks for your issue. The update tool has moved into the official Angular Material repository and now only runs within CLI projects. 

This means that the path to external stylesheets *must* always have the proper extension.
